# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlackTeam',
            fields=[
                ('team_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('access_token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
